### ISSUE TITLE
Prevention and/or response ideas

### ISSUE THREAD

**Issue by GitFezz** [Insider-Threat/Insider-Threat#2]
Thoughts on ‘install UAM’ or ‘capture CLI, keystroke, etc’. And thoughts on ‘Audit/restrict RBAC’

I’m thinking of scenarios about suspected persons, next steps after a detection (automated install of UAM, keystroke logging etc, until can confirm not a threat), or VIP off-obarding.

**Comment by matt-snyder-stuff** [comment]
I added the RBAC as a prevention, good idea!! https://github.com/matt-snyder-stuff/Insider-Threat/blob/master/TTPs/IT1043-Role%20Based%20Access.md

**Comment by matt-snyder-stuff** [comment]
I have been struggling with adding specifics around how to actually detect the activity, I was leaning to having links to published white papers or articles and letting people figure it out on their own. Possibly doing things like a podcast/webinar where we can discuss things there in a more open forum.  It's such a rabbit hole to go down once you start, and I also want to keep it vendor neutral.

**Comment by matt-snyder-stuff** [comment]
But it did give me an idea, one on the Proactive Measures for Logging and Monitoring,  https://github.com/matt-snyder-stuff/Insider-Threat/blob/master/TTPs/IT1044-Logging-Monitoring.md

**Comment by matt-snyder-stuff** [comment]
closing as completed
