### ISSUE TITLE
Business impact / Observable activity

### ISSUE THREAD

**Issue by GitFezz** [Insider-Threat/Insider-Threat#3]
Thought not likely to be directly detectable on your own infrastructure:

- Social media negative sentiment postings (LinkedIn, Reddit, etc)

- Blog postings or anonymous source cited in blog postings

- Leaking of damaging information to 3rd parties for PR purposes - journalists

- Whistleblowing to 3rd party official channels (while we don't of course see this necessarily as a negative, it could be consisted a risk).

**Comment by matt-snyder-stuff** [comment]
closing, these are covered under:

https://github.com/Insider-Threat/Insider-Threat/blob/master/TTPs/IT1033-Malicious%20Social%20Media%20Post.md

https://github.com/Insider-Threat/Insider-Threat/blob/master/TTPs/IT1037-Forwarding%20Internal%20Communications%20to%203rd%20Party.md
