### ISSUE TITLE
Distinction - Insider Threat, Insider Adversary 

### ISSUE THREAD

**Issue by GitFezz** [Insider-Threat/Insider-Threat#9]
Was taking the LinkedIn Learning CSSLP course and heard a fantastic point, made by Jerrod Brennan.  He distinguished between an insider threat and an insider adversary - and I thought it might be worth a mention in the read-me or 'how to use this' type guide.

https://www.linkedin.com/learning/csslp-cert-prep-2-secure-software-requirements/nonfunctional-requirements-9977572?autoSkip=true&contextUrn=urn%3Ali%3AlearningCollection%3A6978923695390040064&resume=false&u=2196553

Its between the 3-4 min mark. I

**Comment by matt-snyder-stuff** [comment]
very good point, thanks for the share!
